service: aws-serverless-upload
frameworkVersion: "3"

custom:
  bucket: "sls-media-bucket"

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-south-1
  logRetentionInDays: 7
  httpApi:
    cors:
      allowedOrigins: "*"
      allowedHeaders: "*"
      allowedMethods:
        - GET
        - POST
        - OPTIONS
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - "s3:Put*"
            - "s3:Get*"
          Resource:
            - arn:aws:s3:::${self:custom.bucket}/*

package:
  individually: true

plugins:
  - serverless-offline

functions:
  upload:
    handler: handler.handler
    events:
      - httpApi: "*"

resources:
  Resources:
    SLSMediaBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucket}
        AccessControl: Private
