service: aws-serverless
frameworkVersion: "3"

custom:
  bucket: "serverless-media-bucket-s3"

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-south-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - "s3:Put*"
            - "s3:Get*"
          Resource:
            - arn:aws:s3:::${self:custom.bucket}/*

functions:
  upload:
    handler: handler.handler
    events:
      - httpApi: "*"

resources:
  Resources:
    MediaUploadBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucket}
        AccessControl: PublicRead